using System.Text.Json;
using Microsoft.Data.Sqlite;
using QuantForge.Core;

namespace QuantForge.Storage;

public sealed class SqliteStrategyGovernanceStore : IStrategyGovernanceStore
{
    private readonly SqliteLocalStore _store;
    public SqliteStrategyGovernanceStore(SqliteLocalStore store) => _store = store;

    public async Task SaveQuarantinedSourceAsync(StrategySourceArtifact artifact, string sourceText, StrategyAuditReport audit, CancellationToken cancellationToken = default)
    {
        if (!string.Equals(artifact.ContentHash, audit.ContentHash, StringComparison.Ordinal)) throw new InvalidOperationException("Artifact/audit fingerprints do not match.");
        await _store.ExecuteGovernanceWriteAsync(async connection => {
            await using var check=connection.CreateCommand(); check.CommandText="SELECT content_hash FROM strategy_sources WHERE source_id=$id;"; check.Parameters.AddWithValue("$id",artifact.SourceId); var existing=await check.ExecuteScalarAsync(cancellationToken);
            if(existing is string h && !string.Equals(h,artifact.ContentHash,StringComparison.Ordinal)) throw new InvalidOperationException("Source ID is already bound to different immutable content.");
            await using var c=connection.CreateCommand(); c.CommandText="INSERT OR IGNORE INTO strategy_sources(source_id,language,content_hash,character_count,acquired_utc,status,source_text,audit_json,audit_fingerprint) VALUES($id,$lang,$hash,$count,$utc,$status,$source,$audit,$fp);";
            c.Parameters.AddWithValue("$id",artifact.SourceId); c.Parameters.AddWithValue("$lang",artifact.Language.ToString()); c.Parameters.AddWithValue("$hash",artifact.ContentHash); c.Parameters.AddWithValue("$count",artifact.CharacterCount); c.Parameters.AddWithValue("$utc",artifact.AcquiredAt.ToString("O")); c.Parameters.AddWithValue("$status",artifact.Status.ToString()); c.Parameters.AddWithValue("$source",sourceText); c.Parameters.AddWithValue("$audit",JsonSerializer.Serialize(audit)); c.Parameters.AddWithValue("$fp",audit.AuditFingerprint); await c.ExecuteNonQueryAsync(cancellationToken);
        }, cancellationToken);
    }

    public async Task<QuarantinedStrategyRecord?> LoadQuarantinedSourceAsync(string sourceId, CancellationToken cancellationToken = default) => await _store.ExecuteGovernanceReadAsync(async connection => {
        await using var c=connection.CreateCommand(); c.CommandText="SELECT language,content_hash,character_count,acquired_utc,status,source_text,audit_json FROM strategy_sources WHERE source_id=$id;"; c.Parameters.AddWithValue("$id",sourceId); await using var r=await c.ExecuteReaderAsync(cancellationToken); if(!await r.ReadAsync(cancellationToken)) return null; var artifact=new StrategySourceArtifact(sourceId,Enum.Parse<StrategySourceLanguage>(r.GetString(0)),r.GetString(1),r.GetInt32(2),DateTimeOffset.Parse(r.GetString(3)),Enum.Parse<StrategySourceStatus>(r.GetString(4))); var audit=JsonSerializer.Deserialize<StrategyAuditReport>(r.GetString(6)) ?? throw new InvalidOperationException("Stored strategy audit is invalid."); return new QuarantinedStrategyRecord(artifact,r.GetString(5),audit);
    }, cancellationToken);

    public async Task SaveSelectionAsync(StrategyComponentSelection selection, CancellationToken cancellationToken = default) => await _store.ExecuteGovernanceWriteAsync(async connection => {
        await using var check=connection.CreateCommand(); check.CommandText="SELECT selection_fingerprint FROM strategy_selections WHERE source_id=$id;"; check.Parameters.AddWithValue("$id",selection.SourceId); var existing=await check.ExecuteScalarAsync(cancellationToken); if(existing is string fp && !string.Equals(fp,selection.SelectionFingerprint,StringComparison.Ordinal)) throw new InvalidOperationException("Source selection is already bound to a different immutable selection fingerprint.");
        await using var c=connection.CreateCommand(); c.CommandText="INSERT OR IGNORE INTO strategy_selections(source_id,selection_fingerprint,selected_features_json,commit_requested,created_utc) VALUES($id,$fp,$features,$commit,$utc);"; c.Parameters.AddWithValue("$id",selection.SourceId); c.Parameters.AddWithValue("$fp",selection.SelectionFingerprint); c.Parameters.AddWithValue("$features",JsonSerializer.Serialize(selection.SelectedFeatureIds.Order(StringComparer.Ordinal))); c.Parameters.AddWithValue("$commit",selection.CommitRequested?1:0); c.Parameters.AddWithValue("$utc",DateTimeOffset.UtcNow.ToString("O")); await c.ExecuteNonQueryAsync(cancellationToken);
    }, cancellationToken);

    public async Task<StrategyComponentSelection?> LoadSelectionAsync(string sourceId, CancellationToken cancellationToken = default) => await _store.ExecuteGovernanceReadAsync(async connection => { await using var c=connection.CreateCommand(); c.CommandText="SELECT selection_fingerprint,selected_features_json,commit_requested FROM strategy_selections WHERE source_id=$id;"; c.Parameters.AddWithValue("$id",sourceId); await using var r=await c.ExecuteReaderAsync(cancellationToken); if(!await r.ReadAsync(cancellationToken)) return null; var set=JsonSerializer.Deserialize<HashSet<string>>(r.GetString(1)) ?? new(); return new StrategyComponentSelection(sourceId,set,r.GetString(0),r.GetInt32(2)!=0); }, cancellationToken);

    public async Task SaveCanonicalModelAsync(CanonicalStrategyModel model, CancellationToken cancellationToken = default) => await _store.ExecuteGovernanceWriteAsync(async connection => {
        await using var check=connection.CreateCommand(); check.CommandText="SELECT model_fingerprint,source_fingerprint FROM canonical_strategy_models WHERE strategy_id=$id;"; check.Parameters.AddWithValue("$id",model.StrategyId); await using var r=await check.ExecuteReaderAsync(cancellationToken); if(await r.ReadAsync(cancellationToken) && (!string.Equals(r.GetString(0),model.ModelFingerprint,StringComparison.Ordinal)||!string.Equals(r.GetString(1),model.SourceFingerprint,StringComparison.Ordinal))) throw new InvalidOperationException("Strategy ID is already bound to different immutable canonical model lineage.");
        await using var c=connection.CreateCommand(); c.CommandText="INSERT OR IGNORE INTO canonical_strategy_models(strategy_id,source_id,source_fingerprint,model_json,model_fingerprint,research_eligible,live_deployment_eligible,created_utc) VALUES($id,$source,$sf,$json,$fp,$research,$live,$utc);"; c.Parameters.AddWithValue("$id",model.StrategyId); c.Parameters.AddWithValue("$source",model.SourceId); c.Parameters.AddWithValue("$sf",model.SourceFingerprint); c.Parameters.AddWithValue("$json",JsonSerializer.Serialize(model)); c.Parameters.AddWithValue("$fp",model.ModelFingerprint); c.Parameters.AddWithValue("$research",model.ResearchEligible?1:0); c.Parameters.AddWithValue("$live",model.LiveDeploymentEligible?1:0); c.Parameters.AddWithValue("$utc",DateTimeOffset.UtcNow.ToString("O")); await c.ExecuteNonQueryAsync(cancellationToken);
    }, cancellationToken);

    public async Task<CanonicalStrategyModel?> LoadCanonicalModelAsync(string strategyId, CancellationToken cancellationToken = default) => await _store.ExecuteGovernanceReadAsync(async connection => { await using var c=connection.CreateCommand(); c.CommandText="SELECT model_json FROM canonical_strategy_models WHERE strategy_id=$id;"; c.Parameters.AddWithValue("$id",strategyId); var v=await c.ExecuteScalarAsync(cancellationToken); return v is string json ? JsonSerializer.Deserialize<CanonicalStrategyModel>(json) : null; }, cancellationToken);

    public async Task AppendLineageAsync(StrategyLineageEvent e, CancellationToken cancellationToken = default) => await _store.ExecuteGovernanceWriteAsync(async connection => { await using var c=connection.CreateCommand(); c.CommandText="INSERT OR IGNORE INTO strategy_lineage(lineage_id,source_id,event_type,subject_fingerprint,parent_fingerprint,created_utc) VALUES($id,$source,$type,$subject,$parent,$utc);"; c.Parameters.AddWithValue("$id",e.LineageId); c.Parameters.AddWithValue("$source",e.SourceId); c.Parameters.AddWithValue("$type",e.EventType); c.Parameters.AddWithValue("$subject",e.SubjectFingerprint); c.Parameters.AddWithValue("$parent",e.ParentFingerprint); c.Parameters.AddWithValue("$utc",e.CreatedAt.ToString("O")); await c.ExecuteNonQueryAsync(cancellationToken); }, cancellationToken);
    public async Task SaveCanonicalSemanticsAsync(CanonicalStrategySemantics semantics, CancellationToken cancellationToken = default) => await _store.ExecuteGovernanceWriteAsync(async connection => {
        await using var check=connection.CreateCommand(); check.CommandText="SELECT semantics_fingerprint,model_fingerprint FROM canonical_strategy_semantics WHERE strategy_id=$id;"; check.Parameters.AddWithValue("$id",semantics.StrategyId); await using var r=await check.ExecuteReaderAsync(cancellationToken); if(await r.ReadAsync(cancellationToken) && (!string.Equals(r.GetString(0),semantics.SemanticsFingerprint,StringComparison.Ordinal)||!string.Equals(r.GetString(1),semantics.ModelFingerprint,StringComparison.Ordinal))) throw new InvalidOperationException("Strategy semantics are already bound to different immutable fingerprints.");
        await using var c=connection.CreateCommand(); c.CommandText="INSERT OR IGNORE INTO canonical_strategy_semantics(strategy_id,model_fingerprint,semantics_json,semantics_fingerprint,created_utc) VALUES($id,$model,$json,$fp,$utc);"; c.Parameters.AddWithValue("$id",semantics.StrategyId); c.Parameters.AddWithValue("$model",semantics.ModelFingerprint); c.Parameters.AddWithValue("$json",JsonSerializer.Serialize(semantics)); c.Parameters.AddWithValue("$fp",semantics.SemanticsFingerprint); c.Parameters.AddWithValue("$utc",DateTimeOffset.UtcNow.ToString("O")); await c.ExecuteNonQueryAsync(cancellationToken);
    }, cancellationToken);

    public async Task<CanonicalStrategySemantics?> LoadCanonicalSemanticsAsync(string strategyId, CancellationToken cancellationToken = default) => await _store.ExecuteGovernanceReadAsync(async connection => { await using var c=connection.CreateCommand(); c.CommandText="SELECT semantics_json FROM canonical_strategy_semantics WHERE strategy_id=$id;"; c.Parameters.AddWithValue("$id",strategyId); var v=await c.ExecuteScalarAsync(cancellationToken); return v is string json ? JsonSerializer.Deserialize<CanonicalStrategySemantics>(json) : null; }, cancellationToken);

}
