<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\QuantForge.Data\QuantForge.Data.csproj" />
    <ProjectReference Include="..\QuantForge.Core\QuantForge.Core.csproj" />
  </ItemGroup>
</Project>
